{% set name = "zoltan" %}
{% set version = "3.83" %}
{% set build = 1 %}

{% set mpi = mpi or 'mpich' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://cs.sandia.gov/Zoltan/Zoltan_Distributions/zoltan_distrib_v{{ version }}.tar.gz
  sha256: f5c866b87e1d17805b934722b0c7d042eaf1c295b472018ef4f35075b8d2cde4
  patches:
    - token-replace.pl.patch

build:
  number: {{ build }}
  skip: true  # [win]
  {% set mpi_prefix = "mpi_" + mpi %}
  string: "{{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}"
  run_exports:
    - {{ name }} * {{ mpi_prefix }}_*

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
  host:
    - {{ mpi }}
    - perl

test:
  commands:
    - test -f ${PREFIX}/include/zoltan.h  # [unix]

about:
  home: http://www.cs.sandia.gov/Zoltan/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYRIGHT_AND_LICENSE
  summary: Parallel Partitioning, Load Balancing and Data-Management Services
  description: |
    The Zoltan Library provides critical data-management services to a wide range of parallel applications.
  doc_url: https://cs.sandia.gov/Zoltan/
  dev_url: https://cs.sandia.gov/Zoltan/ 

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - cekees
    - DavidBrochart
    - rishi9699
